### ISSUE TITLE
XML-RPC limit exceeded error

### ISSUE THREAD

**Issue by mo3rfan** [RaghavPro/SubtitleDownloader#1]
I'm getting this error after first few seconds of running and it stops...

`An error occured while searching sub: int exceeds XML-RPC limits`

**Comment by raghavio** [comment]
Which Python version are you using?
Also, does it happen with all the files or just one?

**Comment by mo3rfan** [comment]
I'm doing a directory wide scan and it happens after some time only (not all the files). Maybe there's a limit to the public OpenSubtitles API?

Python version 2.7.6

**Comment by raghavio** [comment]
No, public one does not have a limit iirc.
But that's not the download limit exceeds error anyway.

I updated it, give it a shot.
